# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yIG2rEd-7IiHapFJSJM5huk5Z-aCm5Zu
"""

# Kalkulyator dasturi

def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    if y != 0:
        return x / y
    else:
        return "Bo‘lish mumkin emas, 0 ga bo‘lish"


print("Amallarni tanlang:")
print("1. Qo‘shish")
print("2. Ayirish")
print("3. Ko‘paytirish")
print("4. Bo‘lish")


choice = input("Tanlang (1/2/3/4): ")


num1 = float(input("Birinchi sonni kiriting: "))
num2 = float(input("Ikkinchi sonni kiriting: "))


if choice == '1':
    print(f"{num1} + {num2} = {add(num1, num2)}")
elif choice == '2':
    print(f"{num1} - {num2} = {subtract(num1, num2)}")
elif choice == '3':
    print(f"{num1} * {num2} = {multiply(num1, num2)}")
elif choice == '4':
    print(f"{num1} / {num2} = {divide(num1, num2)}")
else:
    print("Noto‘g‘ri tanlov")

